hepsi:	derle	calistir

derle:
		
	g++ -I	./include/	-o	./lib/Dugum.o	-c	./src/Dugum.cpp
	g++ -I	./include/	-o	./lib/Liste.o	-c	./src/Liste.cpp
	g++	-I	./include/	-o	./bin/veri	./lib/Dugum.o	./lib/Liste.o	./src/veri.cpp


calistir:
	./bin/veri